### ISSUE TITLE
logo asset tweaks/updates

### ISSUE THREAD

**Issue by missinglink** [pelias/design#1]
Today I uploaded the logo assets provided by [Ura Design](https://ura.design), thanks @elioqoshi & @ergish!

When I started rolling them out across Github I noticed some things that we could improve, which I'm recording in this issue.

- Logos have a generous padding around them which will lead to different padding on various platforms depending on how they are cropped. Could we please apply a 'standard padding' around them? From my testing it seems that very little padding is preferable on Github as the avatar elements are already padded by CSS.

- Following on from above, I found that transparent logos look good on Github (personal preference?) but were not available in the Github folder, I instead cropped one from https://github.com/pelias/design/tree/master/logo/pelias/Pelias%20Logo%20PNG%20Transparent

- There is no vector file of the cute robot 🤖- or a version with a transparent background

**Comment by missinglink** [comment]
<img width="469" alt="Screenshot 2020-04-14 at 15 27 53" src="https://user-images.githubusercontent.com/738069/79230300-a64b3f00-7e64-11ea-96a2-29c9eac7abe5.png">
<img width="309" alt="Screenshot 2020-04-14 at 15 28 19" src="https://user-images.githubusercontent.com/738069/79230301-a77c6c00-7e64-11ea-8fc1-e3538d6e976b.png">

**Comment by ergish** [comment]
Hi @missinglink 

I didn't include them because I thought they would be used with the background in a square shape. 

I am sending now the transparent PNG and vector SVG file for the Pelias Avatar and the Pelias Bot Avatar so using the new files will help in the visual consistency.

About the padding in the images with a background we provided, it helps the logo to be well balanced and centered in a square or round shape. 

In the zip files below I have also included transparent images with less generous padding for GitHub. 

[GitHub Pelias Avatar.zip](https://github.com/pelias/design/files/4475809/GitHub.Pelias.Avatar.zip)
[GitHub Bot Avatar.zip](https://github.com/pelias/design/files/4475808/GitHub.Bot.Avatar.zip)

However, if the logo will be needed for other platforms we will make the right adjustments for each image so just let us know. :)

**Comment by missinglink** [comment]
Excellent thanks! these look great at a small scale which is perfect for a lot of the expected usage ⭐ 

<img width="325" alt="Screenshot 2020-04-15 at 10 34 45" src="https://user-images.githubusercontent.com/738069/79316624-dba76980-7f04-11ea-8836-4cf43ea5f765.png">

**Comment by elioqoshi** [comment]
Wow this actually looks really good on small sizes :)
